framework:
    validation:
        enabled: true
        # Se você estiver usando atributos, certifique-se de que o validador está configurado para suportá-los
        enable_attributes: true  # Em versões mais recentes, o suporte para atributos é padrão

when@test:
    framework:
        validation:
            not_compromised_password: false
