
consultas:
    resource: 
        type: annotation
        path: /consultas
        # Define prefixo para todas as rotas

# Definição de rotas individuais com prefixo aplicado
list:
  path: /
  methods: GET
  controller: App\Controller\ConsultaController::list

create:
  path: /
  methods: POST
  controller: App\Controller\ConsultaController::create

update:
  path: /{id}
  methods: PUT
  requirements:
      id: \d+
  controller: App\Controller\ConsultaController::update

delete:
  path: /{id}
  methods: DELETE
  requirements:
    id: \d+
  controller: App\Controller\ConsultaController::delete
